name: Typescript
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
defaults:
  run:
    working-directory: viewer
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.20.3
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: pnpm
    - name: Install dependencies
      run: pnpm install
    - name: Check Types
      run: pnpm check-types
